### PR TITLE
SDPA-366 : Clicking "Update" on an item creates a new item without th…

### PR DESCRIPTION
**Pull request by naomiaro**
…e old item's content type profile

### CODE REVIEW

**Comment by mdhaman** [comment]
Takes also create new item. You would have to change the https://github.com/superdesk/superdesk-core/blob/master/apps/packages/takes_package_service.py.

**Comment by naomiaro** [comment]
OK cool, I might make a separate ticket to update takes, as this update fix is needed today for PA.

**Comment by mdhaman** [comment]
:+1:  look good. But it would good to have a behave test.

**Comment by mugurrus** [comment]
It would be good to have a test for this.

**Comment by naomiaro** [comment]
OK I'll work on a test to make sure the key profile has been added etc.

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
