### PR TITLE
Add AMAZON_S3_SUBFOLDER to default_settings.py

### PR DESCRIPTION
**Pull request by naspeh**

### CODE REVIEW

**Comment by petrjasek** [comment]
can you also add it to `docs/settings.rst`?

**Comment by naspeh** [comment]
Added to docs.

Maybe we could add this to 1.4 and 1.5 releases too, I think Andrey need this

**Comment by petrjasek** [comment]
:ok:

**Comment by naspeh** [comment]
@petrjasek, please look again, I updated tests regarding new change. Thanks.

**Pull request merged**
