### PR TITLE
Fix teletype formatter

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by marwoodandrew** [comment]
How did I get that wrong?

**Comment by amagdas** [comment]
There is a behave test in superdesk that is failing without this fix. I assume this is the proper use but I could be wrong.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
