### PR TITLE
fix(content_types): fix default values for content profiles

### PR DESCRIPTION
**Pull request by petrjasek**
SD-4626 SD-4625 SD-4624 SD-4622

### CODE REVIEW

**Comment by jerome-poisson** [comment]
looks fine to me, why unique was replaced by iunique ?

**Comment by ioanpocol** [comment]
iunique is unique with ignore letter caps

**Comment by ioanpocol** [comment]
:+1:

**Comment by jerome-poisson** [comment]
ok, so :+1:

**Pull request merged**
