### PR TITLE
Update minimal data for clean setups [SDESK-199]

### PR DESCRIPTION
**Pull request by naspeh**
- we can't use empty vocabularies, so these is one fake item at least
- we can't add kill template via UI, so it also here
- we need validators for publishing, etc.

### CODE REVIEW

**Comment by naspeh** [comment]
I keep this sample data in repo, so you can run `./manage.py app:initialize_data --sample-data` now to get desks, stages, etc.

**Comment by petrjasek** [comment]
would be good to add some info into docs

**Comment by naspeh** [comment]
I'll document this during "Unify deployment" task, there I need to write proper docs for sure

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
