### PR TITLE
update to celery 4

### PR DESCRIPTION
**Pull request by petrjasek**
updating settings names to match changes in 4.0

### CODE REVIEW

**Comment by naspeh** [comment]
Seems it's not enough:
<details>
<summary>Logs from instance: root@sdspr-722:~# tail -f /var/log/superdesk/work.log</summary>
TaskPool: Apply <function _fast_trace_task at 0x7f3295c4d6a8> (args:('superdesk.publish.transmit', 'c0320d81-e005-456a-8430-e68764dd979f', {'argsrepr': '()', 'id': 'c0320d81-e005-456a-8430-e6876
4dd979f', 'correlation_id': 'c0320d81-e005-456a-8430-e68764dd979f', 'kwargsrepr': '{}', 'task': 'superdesk.publish.transmit', 'reply_to': 'b897f0bb-681e-360e-957e-f6e695a3b9e3', 'parent_id': Non
e, 'lang': 'py', 'origin': 'gen247@sdspr-722', 'root_id': 'c0320d81-e005-456a-8430-e68764dd979f', 'timelimit': [None, None], 'delivery_info': {'routing_key': 'publish', 'redelivered': None, 'pri
ority': 0, 'exchange': ''}, 'retries': 0, 'eta': None, 'group': None, 'expires': None}, b'[[], {}, {"callbacks": null, "chord": null, "errbacks": null, "chain": null}]', 'application/json', 'utf
-8') kwargs:{}) level=DEBUG process=MainProcess
Task accepted: apps.publish.enqueue.enqueue_published[ad9c83ac-405f-410b-8c25-2797c81b75a5] pid:294 level=DEBUG process=MainProcess
Task accepted: superdesk.publish.transmit[c0320d81-e005-456a-8430-e68764dd979f] pid:300 level=DEBUG process=MainProcess
Pool callback raised exception: DecodeError(AttributeError("'list' object has no attribute 'get'",),) level=ERROR process=MainProcess
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'chord'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: '_payload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/opt/superdesk/server-core/superdesk/celery_app.py", line 60, in loads
    if not o.get('args', None):
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/billiard/pool.py", line 1748, in safe_apply_callback
    fun(*args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/backends/base.py", line 165, in mark_as_failure
    if request.chord:
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 485, in chord
    _, _, embed = self._payload
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 477, in _payload
    return self.body if self._decoded else self.message.payload
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 207, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 192, in decode
    self._decoded_cache = self._decode()
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 197, in _decode
    self.content_encoding, accept=self.accept)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/opt/superdesk/env/lib/python3.5/site-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/opt/superdesk/server-core/superdesk/celery_app.py", line 60, in loads
    if not o.get('args', None):
kombu.exceptions.DecodeError: 'list' object has no attribute 'get'
Pool callback raised exception: DecodeError(AttributeError("'list' object has no attribute 'get'",),) level=ERROR process=MainProcess
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'chord'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: '_payload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/opt/superdesk/server-core/superdesk/celery_app.py", line 60, in loads
    if not o.get('args', None):
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/billiard/pool.py", line 1748, in safe_apply_callback
    fun(*args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 366, in on_failure
    self.id, exc, request=self, store_result=self.store_errors,
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/backends/base.py", line 165, in mark_as_failure
    if request.chord:
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 485, in chord
    _, _, embed = self._payload
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/opt/superdesk/env/lib/python3.5/site-packages/celery/worker/request.py", line 477, in _payload
    return self.body if self._decoded else self.message.payload
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 207, in payload
    return self._decoded_cache if self._decoded_cache else self.decode()
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 192, in decode
    self._decoded_cache = self._decode()
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/message.py", line 197, in _decode
    self.content_encoding, accept=self.accept)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/opt/superdesk/env/lib/python3.5/site-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/opt/superdesk/env/lib/python3.5/site-packages/kombu/serialization.py", line 263, in loads
    return decode(data)
  File "/opt/superdesk/server-core/superdesk/celery_app.py", line 60, in loads
    if not o.get('args', None):
kombu.exceptions.DecodeError: 'list' object has no attribute 'get'
</details>
I could try to help with this.

**Comment by naspeh** [comment]
We need this:
```
diff --git a/superdesk/celery_app.py b/superdesk/celery_app.py
index 70ee59d..33e7644 100644
--- a/superdesk/celery_app.py
+++ b/superdesk/celery_app.py
@@ -122,6 +122,7 @@ celery.Task = AppContextTask
 
 def init_celery(app):
     celery.config_from_object(app.config, namespace='CELERY')
+    celery.conf.task_protocol = 1
     app.celery = celery
     app.redis = __get_redis(app)
```
http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#new-task-message-protocol

Regarding config names seems it's not critical:
- http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#step-2-update-your-configuration-with-the-new-setting-names
> The changes are *fully backwards compatible,* so you have the option to wait until the old setting names are deprecated, but to ease the transition we have included a command-line utility that rewrites your settings automatically.

**Comment by naspeh** [comment]
In general we probably need to update [superdesk.celery_app.loads](https://github.com/superdesk/superdesk-core/blob/master/superdesk/celery_app.py#L57)

**Comment by naspeh** [comment]
So the simplest way to update `celery` to `4.0.x` is just `CELERY_TASK_PROTOCOL = 1` to `settings.py`

**Comment by petrjasek** [comment]
fixed that json serialization, @naspeh pls let me knows if it works now any better

**Comment by naspeh** [comment]
Important note for production:
> The new protocol is enabled by default in this version and since the new version isn’t backwards compatible you have to be careful when upgrading.

> The 3.1.25 version was released to add compatibility with the new protocol so the easiest way to upgrade is to upgrade to that version first, then upgrade to 4.0 in a second deployment.

So before updating `celery` to `4.x` it should be deployment with `celery==3.1.25` first

**Comment by petrjasek** [comment]
@naspeh given that we use the old protocol, I don't think this applies

**Comment by naspeh** [comment]
Yes, I have missed the line:
`+CELERY_TASK_PROTOCOL = 1`

**Pull request merged**
