### PR TITLE
added new fields to aggregations list

### PR DESCRIPTION
**Pull request by ancafarcas**

### CODE REVIEW

**Comment by akintolga** [comment]
@ancafarcas Are these aggregations for analytics only? If so maybe we should use them only if we're on analytics page.

**Comment by mdhaman** [comment]
These aggregations are used by global search. We have close to 10 million documents in our system. It would be good to keep analytics related aggregates separate.

**Comment by akintolga** [comment]
pinging @mugurrus

**Comment by ancafarcas** [comment]
@akintolga:  Yes, the new aggregations are used only by analytics at the moment. 
@mdhaman: I'm going to talk to Mugur about the possibility of keeping this aggregations only for the analytics

**Pull request merged**
