### PR TITLE
[FEED PARSER][STT NEWSML]implemented new fields/modifications request…

### PR DESCRIPTION
**Pull request by jerome-poisson**
…ed by STT

New fields have been added to STT parser.
A subject scheme can now be specified in SUBJ_QCODE_PREFIXES.
STT NewsML parser can now map location to SD place according to STT_LOCATION_MAP.

SDESK-3507 STTNHUB-14 STTNHUB-18

### CODE REVIEW

**Comment by jerome-poisson** [comment]
I've put the `WIP` label because the location mapping is still in discussion. Also I may create vocabulary automatically when an unknown qcode is found.

**Comment by jerome-poisson** [comment]
Note: this PR is ready and can be reviewed, I'm just keeping the `WIP` label because I'm not sure what to do with `sttcontinent` metadata, I'm currently checking with @karelpetrak .

**Comment by ride90** [comment]
@jerome-poisson why in some places you are using `self.__class__.missing_voc` with `__class__` statement and in some places without?

**Comment by jerome-poisson** [comment]
@ride90 because once the setting is read, it wont change, so I save it in a class attribute, and I need to do it via `self.__class__` (else it would change the instance attribute, not the class one).
When reading the variable, we don't have this problem, so I use `self.missing_voc directly`.

**Pull request merged**
