### PR TITLE
Use released version of Eve

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
@amagdas can we upgrade other repos `superdesk` and `superdesk-content-api` to point to this SHA and also eve to  release instead of branch/commit?

**Comment by sivakuna-aap** [comment]
I just submitted PR's for both repos.

**Comment by amagdas** [comment]
k

**Pull request merged**
