### PR TITLE
LBSD-953 thumbnail available on user

### PR DESCRIPTION
**Pull request by ancafarcas**

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by psnewslab** [comment]
Do you know when this will arrive in liveblog.pro?

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by ancafarcas** [comment]
@psnewslab the change is now available in liveblog: devel branch https://github.com/liveblog/liveblog/tree/devel

**Pull request merged**
