### PR TITLE
Fdl 548 - modified date when updating a published article

### PR DESCRIPTION
**Pull request by mehdignu**

### CODE REVIEW

**Comment by petrjasek** [comment]
how is it different from `versioncreated` ?

**Comment by mehdignu** [comment]
the article's modified date should be changed according to the type of change:
- if grammar correction the modified date should not be updated.
- if republishing modified date should be updated.

**Comment by petrjasek** [comment]
what is republishing?

**Comment by mehdignu** [comment]
change in the content of the article

**Comment by petrjasek** [comment]
why not use correction or update for these?

**Comment by mehdignu** [comment]
We have two versions for updating a published article.
1) only some grammar corrections --> no republishing/ every time stamp stays the same (=modified date will not update)
2) content adjustments or changes --> republishing / time stamp for modified date changes because of the new content inside the article also in FE there should be the modified date displayed*

**Comment by mehdignu** [comment]
We have two versions for updating a published article.
1) only some grammar corrections --> no republishing/ every timestamp stays the same (modified date will not be updated) no changes for date!
2) content adjustments or changes --> republishing / time stamp for modified date changes because of the new content inside the article --> also in FE there should be the modified date displayed

**Pull request closed without merging**
