### PR TITLE
[SD-3097] - Extra carriage returns cleared when a dictionary is uploaded

### PR DESCRIPTION
**Pull request by akintolga**

### CODE REVIEW

**Comment by petrjasek** [comment]
just thinking how is this related to sd-3097?

**Comment by akintolga** [comment]
When a custom dictionary is loaded, it may have `\r` as well as `\n`. if not stripped those words are saved with `\r` at the end (esp if the file is created from a windows based editor). And no words on the editor matches them.

**Comment by petrjasek** [comment]
:+1: makes sense wasn't sure about the case sensitivity

**Comment by mugurrus** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
