### PR TITLE
SDPA-255, SDPA-257

### PR DESCRIPTION
**Pull request by mugurrus**
SDPA-255 Amazon S3 URLs should be dereferenced from Superdesk and use an extension
SDPA-257 Images stored in S3 should be accessible by a configurable Cloudfront URL

### CODE REVIEW

**Comment by ioanpocol** [comment]
./superdesk/storage/amazon/amazon_media_storage.py:26:1: E302 expected 2 blank lines, found 1

./superdesk/storage/amazon/amazon_media_storage.py:57:1: E302 expected 2 blank lines, found 1

**Comment by ioanpocol** [comment]
Some unit&behave tests are required

**Comment by mugurrus** [comment]
Will add some unit tests. Behave tests depend on the test instance being configured for Amazon S3.

**Comment by petrjasek** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by mugurrus** [comment]
Added some unittests

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
