### PR TITLE
fix(settings): don't set SERVER_NAME

### PR DESCRIPTION
**Pull request by actionless**
it's causing issues when attempting to set SUPERDESK_URL with the port other than 80

### CODE REVIEW

**Comment by actionless** [comment]
it's not needed for flask itself and i haven't found it being used by any other superdesk parts

however if it's still required somewhere i could replace that `.endswith(':80'):` with something more universal

**Comment by ioanpocol** [comment]
:+1:

**Comment by actionless** [comment]
oops, it broken flask's `url_for` will do the alternate fix then

**Comment by actionless** [comment]
fixed on the upper level, https://github.com/mitsuhiko/werkzeug/pull/872

idk how soon it will be merged, mb we have to use werkzeug fork then

**Pull request closed without merging**
