### PR TITLE
feat(ninjs): add profile and slugline fields

### PR DESCRIPTION
**Pull request by petrjasek**
- adding profile field to item metadata
- making ninjs formatter keep profile and slugline

not sure how gracefuly can content-api handle schema changes, does it require an update?
ping @amagdas @mugurrus @plamut

### CODE REVIEW

**Comment by amagdas** [comment]
:+1: 
No updates needed to ContentAPI, it will render the new fields correctly.

**Comment by petrjasek** [comment]
hm not sure about it, got 422 response code

**Comment by amagdas** [comment]
Yeah, you are right :(
This needs to be updated:
https://github.com/superdesk/superdesk-content-api/blob/master/content_api/items/resource.py#L14

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
