### PR TITLE
Don't store replaced associated item's metadata in the newly added as associated item. [SDESK-4764]

### PR DESCRIPTION
**Pull request by GyanP**
https://dev.sourcefabric.org/browse/SDESK-4764

### CODE REVIEW

**Comment by GyanP** [comment]
@ride90 @petrjasek is it possible to completely remove the extra keys instead of setting them to None on patch request?

**Comment by ride90** [comment]
Hi @GyanP I think delete is fine.

**Comment by petrjasek** [comment]
I think this won't work for extra:
```py
original['associations']['foo']['extra'] = {'foo': 1}
updates['associations']['foo']['extra'] = {'bar': 1}
```
will produce `{'foo': 1', 'bar': 1}`

**Comment by GyanP** [comment]
> I think this won't work for extra:

good catch, I think this is getting a bit complicated. Isn't there a way around so that we can avoid setting all those keys to None in updates? Simply set `original['associations'][key] = None` and merge updates and original?

**Comment by petrjasek** [comment]
there is a way - set [MERGE_NESTED_DOCUMENTS](https://docs.python-eve.org/en/stable/config.html) to `False`. problem is it's only supported in eve 0.8 so it would require an update. which we should do anyhow..

**Comment by ride90** [comment]
@petrjasek @GyanP since it may take us some time to update to Eve 0.8 (http://docs.python-eve.org/en/stable/changelog.html#id85), we should somehow safety prevent the issue described in the ticket (don't overwrite nested docs), I was able to repeat it quite often playing with Belga images, it results in a wrong data in DB and in output.
@GyanP it's good that only one method handles it, so after an update, it will be easy to erase this logic. Just add a comment to that method, so we know how and why we should erase it. 
It would be good to have a ticket for Eve update with reference to this pr/ticket there.

**Comment by petrjasek** [comment]
maybe we could also try to backport that config into older eve - imo it's not a big change - to avoid all those workarounds, and upgrade eve later

**Comment by ride90** [comment]
@GyanP @petrjasek I've created a ticket to update an eve https://dev.sourcefabric.org/browse/SDESK-4968

**Pull request closed without merging**
