### PR TITLE
Move Amazon S3 storage to core

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
an idea - maybe we can put those test files into `tests` folder outside of `superdesk` folder, when you use the library you probably don't need those (i mean the actual unit tests, not the tests setup)

**Comment by amagdas** [comment]
Yup, it makes sense, will do it in next PR.

**Comment by amagdas** [comment]
Actually I will add to this PR.

**Comment by amagdas** [comment]
@petrjasek done

**Comment by petrjasek** [comment]
ok only not sure how it works with `find_packages` in setup, I think it should be updated

**Comment by petrjasek** [comment]
to `find_packages(exclude=['tests'])`

**Comment by amagdas** [comment]
Right, too sleepy

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
