### PR TITLE
Use field label instead of ID in content filters

### PR DESCRIPTION
**Pull request by tomaskikutis**
SDESK-4538

### CODE REVIEW

**Comment by tomaskikutis** [comment]
@petrjasek can you point me to an example on how to translate the labels?

**Comment by petrjasek** [comment]
```py
from flask_babel import _
...
'label': _('ANPA Category'),
```

**Comment by tomaskikutis** [comment]
Thanks. And how do I verify that it works? Will the same translations be shared between client/server?

**Comment by petrjasek** [comment]
I don't think we have it working now e2e

**Comment by tomaskikutis** [comment]
what do you mean by e2e? That sharing translations between client/server doesn't work, or that translating itself doesn't work? :smile:

**Comment by petrjasek** [comment]
I mean sharing translations

**Pull request merged**
