### PR TITLE
(feat) Modified priority to use values from 1-6.

### PR DESCRIPTION
**Pull request by mdhaman**
Resolves: [SD-2627](https://dev.sourcefabric.org/browse/SD-2627)

Reverting `bcrypt` back to `1.1.0` as hash value of password while authenticating and hash value of password while persisting into DB are different and causing Authentication failure.

https://github.com/superdesk/superdesk/pull/1301

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by amagdas** [comment]
Is there any corresponding PR in SD?

**Comment by mdhaman** [comment]
yes. i will do it after our show and tell.

**Pull request merged**
