### PR TITLE
fix(celery): handle errors with app.context

### PR DESCRIPTION
**Pull request by petrjasek**
when sending notifications on ingest error it was out
of application context and thus raising runtime error.

now all error handing is done in celery task `on_failure`
callback using application context.

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
had to rework this, was still failing on some ingest errors

**Comment by amagdas** [comment]
OK :+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
