### PR TITLE
fix(renditions): keep renditions until expiry

### PR DESCRIPTION
**Pull request by petrjasek**
instead of removing old renditions on update, it will remove
these for all versions when item expires.

SDESK-429

### CODE REVIEW

**Comment by mdhaman** [comment]
@petrjasek but with this approach we would have picture items not expiring from production.

**Comment by petrjasek** [comment]
@mdhaman exactly. still figuring out the workflow for those

**Comment by petrjasek** [comment]
@mdhaman removed that embedded handling

**Comment by mdhaman** [comment]
@thanks petr

**Pull request merged**
