### PR TITLE
[DICTIONARIES] work around Eve behaviour which create sub-dict on eac…

### PR DESCRIPTION
**Pull request by jerome-poisson**
…h "." it find in keys

this works by using Flask's request object and overwritting the content
of updates (which comes after Eve) with it.

SDESK-3083

### CODE REVIEW

**Comment by petrjasek** [comment]
can you add a test for it?

**Comment by jerome-poisson** [comment]
@petrjasek I haven't made a test because the issue is due to behaviour with Eve during real request, and we need to use Flask to fix it, I'm not sure we can easily simulate that in a realistic way without launching client. I can try to mock, I'll check it out.

**Comment by petrjasek** [comment]
imo it should be possible via behave test

**Comment by jerome-poisson** [comment]
@petrjasek FYI I've added the tests. Indeed with behave it's doing the whole workflow, so tests make sense, thanks for the feedback.

**Comment by tomaskikutis** [comment]
I've created an issue on eve repo to address this bug https://github.com/pyeve/eve/issues/1173

**Pull request merged**
