### PR TITLE
Feature/s3 version enhancement

### PR DESCRIPTION
**Pull request by nistormihai**

### CODE REVIEW

**Comment by nistormihai** [comment]
I need review

**Comment by petrjasek** [comment]
:+1: so this creates a new folder on amazon every 15m right?

**Comment by nistormihai** [comment]
yes, but not only that. I added also the option to opt out for versioning or to give one as you want.

**Comment by petrjasek** [comment]
cool

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
