### PR TITLE
SDPA-152 All uploaded, cropped or manipulated images should be referenced by an S3 HTTPS url

### PR DESCRIPTION
**Pull request by mugurrus**

### CODE REVIEW

**Comment by vied12** [comment]
:+1:

**Comment by ioanpocol** [comment]
We can add a few behave tests that will run only if the amazon related settings are set.
We have to store original urls to amazon and create the proxy url only on fetch.
Right now the files on amazon are public. Do we intend to implement any security scheme on them?

**Comment by ioanpocol** [comment]
:+1:  (except comments)

**Comment by mugurrus** [comment]
Behave tests and generate URL on fetch in a separate PR

**Pull request merged**
