### PR TITLE
refactor(apps): move apps into core

### PR DESCRIPTION
**Pull request by petrjasek**
so idea is to put more or less everything into core repo (and we might rename this to -server at some point). then in main repo you import this with pip and with settings you enable/disable things

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1: 
Are we moving also the frontend part on superdesk-core?

**Comment by petrjasek** [comment]
@ioanpocol into it's own repo, but same thing

**Comment by mugurrus** [comment]
Why put AAP code in the central repo?

**Comment by petrjasek** [comment]
@mugurrus can you be more specific?

**Comment by mugurrus** [comment]
e.g. https://github.com/superdesk/superdesk/tree/master/server/apps/publish/formatters

**Comment by mdhaman** [comment]
:+1: All Good. Formatters can be moved later on.

**Comment by akintolga** [comment]
:+1: Agree.

**Pull request merged**
