### PR TITLE
[SD-4301] Fixing the problem where archive kill not working.

### PR DESCRIPTION
**Pull request by mdhaman**
@petrjasek for eve-elastic if `req.args` is not passed and lookup is used then it throws exception at https://github.com/petrjasek/eve-elastic/blob/master/eve_elastic/elastic.py#L358. 

I have done [PR Eve-Elastic](https://github.com/petrjasek/eve-elastic/pull/60) for that as well.

### CODE REVIEW

**Comment by petrjasek** [comment]
you can use `eve-elastic==0.3.7` now

**Comment by mugurrus** [comment]
:+1:

**Comment by mdhaman** [comment]
@petrjasek done

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
