### PR TITLE
[manage] [data:upgrade] fixed bad argument handling

### PR DESCRIPTION
**Pull request by jerome-poisson**
entity_name can be used as string or list, this commit check the type
to handle the loop correclty, and avoid a KeyError exception.

fixes SDESK-574

### CODE REVIEW

**Comment by jerome-poisson** [comment]
@petrjasek @naspeh I've updated the P.R. with docstring, and added a check on path/sample_data. Also changed default values for boolean from None to False. If you're happy with the changes (and if travis is happy too), this can be merged

**Comment by naspeh** [comment]
flake8 is not happy :)
```
++ flake8 --jobs=1
./apps/prepopulate/app_initialize.py:218:1: D403 First word of the first line should be properly capitalized
```

**Comment by naspeh** [comment]
overall it looks good, thanks!

**Comment by jerome-poisson** [comment]
arf, I usually run it before, but I was too confident this time :)

**Pull request merged**
