### PR TITLE
[SD-4057] - Optional unique field for vocabulary items

### PR DESCRIPTION
**Pull request by akintolga**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by akintolga** [comment]
@actionless @petrjasek Would you please update the vocabularies in master whenever you have time using the following command,  not urgent though. Thanks.
`python manage.py vocabularies:populate -f data/vocabularies.json`

**Comment by actionless** [comment]
@akintolga it throwed bunch of similar exceptions:
```
--- Logging error ---                                                                                              [1060/1383]
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "manage.py", line 22, in <module>
    manager.run(superdesk.COMMANDS)
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/__init__.py", line 56, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 56, in run
    process_vocabularies(filepath)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 44, in process_vocabularies
    populate_vocabularies(json_data)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 27, in populate_vocabularies
    service.put(id_name, item)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/services.py", line 129, in put
    self.on_replace(document, original)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/vocabularies.py", line 70, in on_replace
    logger.info("updating vocabulary", document["_id"])
Message: 'updating vocabulary'
Arguments: ('categories',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/handlers.py", line 883, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "manage.py", line 22, in <module>
    manager.run(superdesk.COMMANDS)
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/__init__.py", line 56, in __call__
    res = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 56, in run
    process_vocabularies(filepath)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 44, in process_vocabularies
    populate_vocabularies(json_data)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/command.py", line 27, in populate_vocabularies
    service.put(id_name, item)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/services.py", line 129, in put
    self.on_replace(document, original)
  File "/usr/local/lib/python3.4/dist-packages/superdesk/vocabularies/vocabularies.py", line 70, in on_replace
    logger.info("updating vocabulary", document["_id"])
Message: 'updating vocabulary'
Arguments: ('categories',)
```

**Comment by akintolga** [comment]
As far I can see they are only thrown by the logger so I think update is still good. Thanks.

**Pull request merged**
