### PR TITLE
fix(dictionaries): store big dictionaries into gridfs

### PR DESCRIPTION
**Pull request by petrjasek**
when it gets bigger, store it in gridfs, otherwise keep it in doc

SD-4986

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by petrjasek** [comment]
@akintolga updated that store method, so it will handle those cases properly.

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
