### PR TITLE
[SD-5402] Category mapping for PA ingest

### PR DESCRIPTION
**Pull request by marwoodandrew**

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
I think this parser should be located on superdesk/pa branch since it is custom for PA

**Comment by marwoodandrew** [comment]
This is for AAP (or anyone else) to parse PA sourced NITF! There could be an argument that it belongs in the AAP branch. The problem was that we were routing the content based in the IPTC code, but it seems not all articles has IPTC codes present. So mapped the PA specific category to ANPA categories in Superdesk.

**Comment by ioanpocol** [comment]
OK, now I understood.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
