### PR TITLE
(imp) [SD-3650] Page refreshing is required for vocabulary changes to take effect

### PR DESCRIPTION
**Pull request by sivakuna-aap**
Resolves: [SD-3650](https://dev.sourcefabric.org/browse/SD-3650)
Required by: https://github.com/superdesk/superdesk/pull/1392

### CODE REVIEW

**Comment by plamut** [comment]
Maybe consider adding a test or two, though it looks good IMO.

**Comment by sivakuna-aap** [comment]
It's already been taken care in superdesk pr https://github.com/superdesk/superdesk/pull/1392

**Comment by plamut** [comment]
OK, good then.

:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
