### PR TITLE
[SD-4134] Change genre vocabulary to use qcode rather than value

### PR DESCRIPTION
**Pull request by marwoodandrew**
As a an initial part of making the vocabularies constant, change the use of value to qcode in genre.

### CODE REVIEW

**Comment by mdhaman** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by ahilles107** [comment]
:+1:

**Comment by petrjasek** [comment]
just wondering if we should call it qcode, because without having some id of the vocabulary it isn't a qcode really, you need to know where it comes from. it's more like a code in ninjs
> The code for the subject in a scheme (= controlled vocabulary) which is identified by the scheme property

**Comment by marwoodandrew** [comment]
I think that the aim is to make the structure of the vocabulary entries constant to simplify/unify the handling of them.

**Comment by ioanpocol** [comment]
please rebase

**Comment by petrjasek** [comment]
:+1: just wondering what should be the property name, agree with the changes

**Comment by mdhaman** [comment]
do we need to store the scheme definition with `qcode|code` in the mongo (anpa_category:a) or it is a concern for output formatters?

**Comment by petrjasek** [comment]
I think in vocabulary it should be `code` and scheme is vocabulary id, but on an item we should have either `code` + `scheme` or `qcode` which combines both.

**Comment by akintolga** [comment]
Merging as it is needed for e2e tests...

**Comment by petrjasek** [comment]
no worries

**Pull request merged**
