### PR TITLE
[SD-5407] default AP categories, and remove undefined categories from…

### PR DESCRIPTION
**Pull request by marwoodandrew**
… items on ingest

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by petrjasek** [comment]
not sure if it's urgent, but if so you can set milestone to 1.1 and when this is merged I will cherry pick it to 1.1 branch

**Comment by marwoodandrew** [comment]
Not urgent 1.2 would be fine. A very small percentage of stories from AP have this problem, they just happened to fetch one!

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
