### PR TITLE
Sdntb 328

### PR DESCRIPTION
**Pull request by jerome-poisson**
use lxml and pretty print output

### CODE REVIEW

**Comment by ioanpocol** [comment]
@jerome-poisson @petrjasek Should we add this PR to 1.4?

**Comment by petrjasek** [comment]
no, we shouldn't add features to older releases, we will have to use 1.6 for ntb

**Comment by ioanpocol** [comment]
OK, in this case we need a 1.4 branch on superdesk-ntb too.

**Comment by petrjasek** [comment]
what for?

**Comment by ioanpocol** [comment]
On superdesk-ntb there is a PR that needs this PR. We need a branch without that PR.

**Comment by petrjasek** [comment]
and it's merged? what PR is it?

**Comment by ioanpocol** [comment]
https://github.com/superdesk/superdesk-ntb/pull/55
Merged 6 days ago.

**Comment by petrjasek** [comment]
and what's the issue with it? if we update to 1.6 it should work

**Comment by ioanpocol** [comment]
If the next update to ntb production is 1.6, yes it is ok. If there are some fixes on 1.4 that should be deployed, we need to create branch 1.4 on superdesk-ntb.

**Comment by petrjasek** [comment]
ah I see, so not needed atm, but if there is some hotfix for 1.4, we would need it, right?

**Comment by ioanpocol** [comment]
yes, there are already a few fixes added to 1.4 branch and also to master, but I don't know when should be deployed.

**Comment by jerome-poisson** [comment]
Can't we cherry pick the fixes without the changes on lxml?

**Comment by petrjasek** [comment]
all fixes will be in 1.6, I think it's now

**Pull request merged**
