### PR TITLE
fix(workqueue): When an item is opened for correction it will show up on the bottom panel (SD-3556)

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
looks ok, but can you nelu explain a bit the solution? just wondering how it fixes the issue

**Comment by sivakuna-aap** [comment]
I think this solution might be a performance hit as archive repository in Mongo can have million(s) of docs and since workqueue is visible always, every operation on the article hits the workqueue endpoint.

Is there a corresponding PR in superdesk-client-core?

**Comment by ioanpocol** [comment]
Changed to use elastic instead of mongodb

**Pull request merged**
