### PR TITLE
crop updates

### PR DESCRIPTION
**Pull request by petrjasek**
- moving `archive_crop` module into core as `superdesk.crop`
- let `crop_image` also resize to given width/height if provided

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:  Looks Good.  Any specific reason for not having `crop.py` in `superdesk.media`?

**Comment by petrjasek** [comment]
didn't think about that module, it should be there, will update this

**Comment by ioanpocol** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
