### PR TITLE
[SD-4494] (feat) Modified dictionary to store abbreviations and expanded phrase for the abbreviations.

### PR DESCRIPTION
**Pull request by mdhaman**
This will allow the user to store abbreviation and expanded phrase.

- [x] Behave test.

### CODE REVIEW

**Comment by akintolga** [comment]
:+1:  Does existing behave test for dictionary cover the new changes?

**Comment by mdhaman** [comment]
@akintolga  no it does not. Add couple more behave test.

**Comment by akintolga** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
